import Head from "next/head";
import {
  BsFillMoonStarsFill,
  BsGithub,
  BsLinkedin,
  BsMailbox,
} from "react-icons/bs";
import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiReact,
  SiBootstrap,
  SiMui,
  SiTailwindcss,
  SiFirebase,
  SiNodedotjs,
  SiMongodb,
  SiExpress,
  SiNextdotjs,
  SiFigma,
  SiPostman,
} from "react-icons/si";
import Image from "next/image";
import Avatar from "../../public/nobg-avatar.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Can Yapalak Portfolio</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-around">
            <h1 className="text-2xl font-cocogoose">portfolio</h1>
            <ul className="flex items-center gap-5">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md font-cocogooseprolight text-sm"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center py-5 px-10 font-cocogooseprolight">
            <h2 className="text-3xl py-2 text-cyan-600 font-medium">
              Can Yapalak
            </h2>
            <h3 className="text-xl py-2">Junior Web Developer</h3>
            <p className="text-sm py-2">
              👋 I'm Can, a fresh Junior Web Developer residing in Berlin,
              Germany.
              <br></br>
              🌱 I'm currently learning how to be a Full-Stack Web Dev and
              spending all my time and energy in this new field of expertise.
              <br></br>💞️ I aim to start working as a full-time web developer
              and keep on progressing with experience.
            </p>
          </div>
          <div className="text-3xl flex justify-center gap-7 text-cyan-600 mb-10">
            <a target="_blank" href="https://github.com/canyapalak">
              <BsGithub />
            </a>
            <a
              target="_blank"
              href="https://www.linkedin.com/in/can-yapalak-a1359b76/"
            >
              <BsLinkedin className="cursor-pointer" />
            </a>
            <a target="_blank" href="mailto:canyapalak@gmail.com">
              <BsMailbox className="cursor-pointer" />
            </a>
          </div>
          <div
            className="relative mx-auto bg-gradient-to-b
          from-slate-500 rounded-full w-60 h-60 overflow-hidden
          shadow-xl"
          >
            <Image src={Avatar} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section className="mt-5 min-h-screen">
          <div className="font-cocogooseprolight max-w-40 pt-40">
            <h3 className="text-xl text-center pb-2 mb-5">My Skills</h3>
            <p className="text-sm px-5 pb-10 text-center max-w-screen-lg mx-auto ">
              This is my toolbox so far. I tend to learn a new tool in every new
              project and gain more experience on what I have learned before. In
              this way, I aim to expand my toolbox as soon as possible. My
              purpose is to get familiar with most of the libraries, frameworks
              and environments that are widely used in the industry.
            </p>
          </div>
          <div
            className="flex flex-wrap justify-around
          gap-5 p-10 rounded-lg bg-gradient-to-b
          from-teal-300 shadow-md mb-10 max-w-screen-sm mx-auto "
          >
            <a
              target="_blank"
              href="https://www.w3schools.com/html/default.asp"
            >
              <SiHtml5 className="text-6xl" />
            </a>
            <a target="_blank" href="https://www.w3schools.com/css/default.asp">
              <SiCss3 className="text-6xl" />
            </a>
            <a target="_blank" href="https://www.javascript.com/">
              <SiJavascript className="text-6xl" />
            </a>
            <a target="_blank" href="https://reactjs.org/">
              <SiReact className="text-6xl" />
            </a>
            <a target="_blank" href="https://getbootstrap.com/">
              <SiBootstrap className="text-6xl" />
            </a>
            <a href="https://mui.com/">
              <SiMui className="text-6xl" />
            </a>
            <a target="_blank" href="https://tailwindcss.com/">
              <SiTailwindcss className="text-6xl" />
            </a>
            <a target="_blank" href="https://firebase.google.com/">
              <SiFirebase className="text-6xl" />
            </a>
            <a target="_blank" href="https://nodejs.org/en/">
              <SiNodedotjs className="text-6xl" />
            </a>
            <a target="_blank" href="https://www.mongodb.com/">
              <SiMongodb className="text-6xl" />
            </a>
            <a target="_blank" href="https://expressjs.com/">
              <SiExpress className="text-6xl" />
            </a>
            <a target="_blank" href="https://nextjs.org/">
              <SiNextdotjs className="text-6xl" />
            </a>
            <a target="_blank" href="https://www.figma.com/">
              <SiFigma className="text-6xl" />
            </a>
            <a target="_blank" href="https://www.postman.com/">
              <SiPostman className="text-6xl" />
            </a>
          </div>
        </section>
      </main>
    </div>
  );
}
